### ISSUE TITLE
Sick_scan on Windows 10

### ISSUE THREAD

**Issue by Mecatropabien** [SICKAG/sick_scan_base#9] opened 2021-03-01 14:23 UTC
Hello,

I'm working on a TIM240 and I would like to use sick_scan on Windows 10. I had some trouble first because some librairies (inet.h, socket.h) are for Unix.
Sick send me a link to a closed issue which can help me : https://github.com/SICKAG/sick_scan_base/issues/6

I saw your recommandations and I installed vcpkg, boost and pthread. But I don't understand the next step about build.bat.
which build.bat ? Where I can find it ?
![sick_scan issue](https://user-images.githubusercontent.com/79853653/109510126-ef6aa880-7aa1-11eb-9f86-2cb0a6ad2524.PNG)

Thank you in advance for your response.
Best regards,
Julien REY.

**Comment by michael1309** [comment] 2021-03-04 14:28
[build.zip](https://github.com/SICKAG/sick_scan_base/files/6084302/build.zip)
Hi Julien,

find attached a build.bat as an example, which could/should be modified to your Visual Studio version. Please store this file into the root-project-directory (i.e. same position as CMakeLists.txt)

Best regards,
Michael

**Comment by Mecatropabien** [comment] 2021-03-05 07:20
Hello Michael,

Thank you for your reply. I put it into the root-directory and I executed build.bat.
I have still some errors and I don’t understand why. I send you a screen. Could you please help me with this ?
Maybe I don’t use the correct command… I just execute “build.bat” in the Native command prompt for VS 2019 in the directory where the .bat is.

Thank you in advance.
Best regards,
Julien REY.

De : Michael Lehning <notifications@github.com>
Envoyé : jeudi 4 mars 2021 15:29
À : SICKAG/sick_scan_base <sick_scan_base@noreply.github.com>
Cc : REY Julien <julien.rey@fivesgroup.com>; Author <author@noreply.github.com>
Objet : Re: [SICKAG/sick_scan_base] Sick_scan on Windows 10 (#9)

[Email émis par un expéditeur externe au groupe Fives : soyez prudent avec les liens et les pièces jointes]

build.zip [github.com]<https://urldefense.com/v3/__https:/github.com/SICKAG/sick_scan_base/files/6084302/build.zip__;!!FzVXsuqP!Bg4Grd73I4hBY29_YPaBP6STk2tDn89o516MwxNtOMzAsbFZjn7PvuNowCyTI_ZPkRFx$>
Hi Julien,

find attached a build.bat as an example, which could/should be modified to your Visual Studio version. Please store this file into the root-project-directory (i.e. same position as CMakeLists.txt)

Best regards,
Michael

**Comment by michael1309** [comment] 2021-03-08 14:38
I can not seen your screenshot It this ticket a duplicate of https://github.com/SICKAG/sick_scan/issues/115 ?

Best regards,
Michael

**Comment by michael1309** [comment] 2021-03-09 16:13
Solved using WSL2 (see https://github.com/SICKAG/sick_scan_base/issues/115 )

**Comment by michael1309** [comment] 2021-03-09 16:14
Solved using WSL2 (see https://github.com/SICKAG/sick_scan/issues/115 )

**Closed by michael1309** 2021-03-09 16:13 UTC
